---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jaec/public_html/test
    - chmod -R 0775 $DEPLOYPATH/storage
    - chmod -R 0775 $DEPLOYPATH/bootstrap/cache
    - cd $DEPLOYPATH && php artisan config:clear 2>&1 || true
    - cd $DEPLOYPATH && php artisan route:clear 2>&1 || true
    - cd $DEPLOYPATH && php artisan view:clear 2>&1 || true
